# Generated by Django 5.1.5 on 2025-07-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_historicalproductsubcatagory_productsubcatagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproductsubcatagory',
            old_name='Organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='productsubcatagory',
            old_name='Organization',
            new_name='organization',
        ),
    ]
