# Generated by Django 5.1.5 on 2025-07-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_rename_organization_historicalproductsubcatagory_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproductsubcatagory',
            old_name='productCategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productsubcatagory',
            old_name='productCategory',
            new_name='category',
        ),
    ]
