# Generated by Django 5.1.5 on 2025-07-30 05:28

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_alter_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=upload.models.path_and_rename),
        ),
    ]
