# Generated by Django 5.1.5 on 2025-07-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_historicalproduct_model_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='eol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='eol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
