# Generated by Django 5.1.5 on 2025-07-31 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_rename_productcategory_historicalproductsubcatagory_category_and_more'),
        ('products', '0016_historicalproduct_eol_product_eol'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='product_sub_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.productsubcatagory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.productsubcatagory'),
        ),
    ]
